spring:
  config:
    import: env.yml
    data:
      redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}
        pool:
          max-idle: ${REDIS_POOL_MAX_IDLE}
          min-idle: ${REDIS_POOL_MIN_IDLE}
          max-active: ${REDIS_POOL_MAX_ACTIVE}
          max-wait: ${REDIS_POOL_MAX_WAIT}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
        mime:
          charset: UTF-8
        transport:
          protocol: smtp


  datasource:
    url: jdbc:mysql://${DATABASE_HOST}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy


  thymeleaf:
    prefix: classpath:/mail-templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false
